services:
  aiolists:
    build:
      context: https://github.com/SebastianMorel/AIOLists.git
      dockerfile: Dockerfile
    container_name: aiolists
    restart: unless-stopped
    ports:
      - 7000:7000
    env_file:
      - .env
    profiles:
      - required
